_configs = {
    'memory':{
        'llm':{
            'verbose':True
        },
        'FileChatMessageHistory':{
            'file_path':'data/messages.json'
        },
        'ConversationSummaryMemory':{
            'memory_key':'messages',
            'return_messages':True
        },
    },
    'prompt':{
        'ChatPromptTemplate':{
            'input_variables':['content', 'messages']
        },
        'MessagesPlaceholder':{
            'variable_name':'messages'
        },
        'HumanMessagePromptTemplate':{
            'template':'{content}'
        }
    },
    'llm_chain':{
        'llm_chain':{
            'verbose':True
        }
    }
}