_configs_boxen = {
    'system':{
        'color':'yellow'
    },
    'human':{
        'color':'green'
    },
    'ai-function':{
        'color':'cyan'
    },
    'ai':{
        'color':'blue'
    },
    'function':{
        'color':'purple'
    },
    'else':{
        'color':'white'
    }
}
